spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost:3306/splitinam
spring.datasource.username=root
spring.datasource.password=8Tol13j4i-19
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true